<a href="https://colab.research.google.com/github/mahaapoorani/Machine-Learning-Projects/blob/main/decision_tree_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df= pd.read_csv("/content/housing.csv")

In [2]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [3]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [4]:
df["total_bedrooms"]=df["total_bedrooms"].fillna(df["total_bedrooms"].mean())

In [5]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [6]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

In [10]:
X= df.drop("median_house_value",axis=1)
Y=df["median_house_value"]

In [15]:
X.shape

(20640, 9)

In [16]:
Y.shape

(20640,)

In [17]:
X.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
ocean_proximity       0
dtype: int64

In [20]:
X= pd.get_dummies(X, columns= ['ocean_proximity'])

In [21]:
X.shape
X.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,False,False,False,True,False
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,False,False,False,True,False
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,False,False,False,True,False
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,False,False,False,True,False
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,False,False,False,True,False

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X,Y, test_size=0.2, random_state=42)

In [50]:
from sklearn.tree import DecisionTreeRegressor
model= DecisionTreeRegressor(max_depth=10)
model.fit(X_train, Y_train)

DecisionTreeRegressor(max_depth=10)

In [51]:
Y_pred= model.predict(X_test)
print(Y_pred[:10])

[ 61206.32911392  66479.54545455 439405.         227714.08450704
 206504.05       163056.38297872 204294.26751592 174800.90634441
 260569.59695817 488239.23076923]

In [52]:
for i in range(5):
  print(f"ACTUAL: {Y_train.iloc[i]}")
  print(f"PREDICTED: {Y_pred[i]}")
  print("-"*30)

ACTUAL: 103000.0
PREDICTED: 61206.329113924054
------------------------------
ACTUAL: 382100.0
PREDICTED: 66479.54545454546
------------------------------
ACTUAL: 172600.0
PREDICTED: 439405.0
------------------------------
ACTUAL: 93400.0
PREDICTED: 227714.08450704225
------------------------------
ACTUAL: 96500.0
PREDICTED: 206504.05
------------------------------

In [53]:
print("Train Score:", model.score(X_train, Y_train))
print("Test Score:", model.score(X_test, Y_test))

Train Score: 0.82338538379199
Test Score: 0.708335336764326

In [54]:
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeRegressor

for depth in [8, 10, 12, 15]:
    model = DecisionTreeRegressor(max_depth=depth)
    model.fit(X_train, Y_train)
    Y_pred_loop = model.predict(X_test)
    mae = mean_absolute_error(Y_test, Y_pred_loop)
    print(f"Max Depth: {depth}, MAE: {mae:.2f}")

Max Depth: 8, MAE: 42766.37
Max Depth: 10, MAE: 40698.56
Max Depth: 12, MAE: 40589.46
Max Depth: 15, MAE: 41374.44