<a href="https://colab.research.google.com/github/mahaapoorani/Machine-Learning-Projects/blob/main/Random_forest_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df= pd.read_csv("/content/housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [3]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [4]:
df["total_bedrooms"]=df["total_bedrooms"].fillna(df["total_bedrooms"].mean())

In [5]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [6]:
X= df.drop("median_house_value",axis=1)
y=df["median_house_value"]
X.shape
y.shape

(20640,)

In [9]:
X=pd.get_dummies(X, columns=["ocean_proximity"])

In [10]:
X.shape

(20640, 13)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size= 0.2, random_state= 42)

In [27]:
from sklearn.ensemble import RandomForestRegressor
model= RandomForestRegressor(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [28]:
y_pred=model.predict(X_test)

In [29]:
from sklearn.metrics import mean_absolute_error, r2_score
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Train Score:", model.score(X_train, y_train))
print("Test Score:", model.score(X_test, y_test))
print("MAE:", mae)
print("R² Score:", r2)

# Actual vs Predicted

print("\nActual vs Predicted:\n")

for actual, predicted in zip(y_test[:5], y_pred[:5]):
    print(f"ACTUAL: {actual:.2f}")
    print(f"PREDICTED: {predicted:.2f}")
    print("-" * 30)

Train Score: 0.9760904663266143
Test Score: 0.8181529346949161
MAE: 31522.390436046513
R² Score: 0.8181529346949161

Actual vs Predicted:

ACTUAL: 47700.00
PREDICTED: 53371.50
------------------------------
ACTUAL: 45800.00
PREDICTED: 69765.00
------------------------------
ACTUAL: 500001.00
PREDICTED: 467286.90
------------------------------
ACTUAL: 218600.00
PREDICTED: 255855.50
------------------------------
ACTUAL: 278000.00
PREDICTED: 267666.00
------------------------------